SweetPie/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path , include
from . import views
app_name="music"
urlpatterns = [
    path('', views.Index, name="index"),
    path('register/',views.Register,name="register"),
    path('login/',views.loginView,name="login"),
    path('logout/',views.logoutView,name="logout"),

    path('addalbum/',views.albumCreate,name="add-album"),
    path('albums/',views.albums.as_view(),name="albums"),
    path('albums/<int:id>/',views.DetailView.as_view(),name="detail"),
    path('albums/<int:id>/delete',views.DeleteAlbum.as_view(),name="delete-album"),
    path('albums/<int:id>/addsong/',views.CreateSong,name="add-song"),
    path('albums/<int:album_id>/DeleteSong/<int:song_id>',views.DeleteSong,name="song-delete"),
    
    path('albums/<int:album_id>/song_public/<int:song_id>/',views.song_is_public,name="song_public"),
    path('albums/<int:album_id>/song_favorite/<int:song_id>/',views.song_is_favorite,name="song_favorite"),

    path('albums/<int:album_id>/album_public/',views.album_is_public,name="album_public"),
    path('albums/profile/',views.profile.as_view(),name="profile"),
    path('albums/songs/',views.songs,name="songs"),
    ]

music/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

from django.urls import reverse

# Create your models here.
class Album(models.Model):
    user = models.ForeignKey(User, default=1 , on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    artist = models.CharField(max_length=50)
    album_file = models.FileField(null=True)
    is_public = models.BooleanField(default='False')
    def get_absolute_url(self):
        return reverse("music:detail", kwargs={"id": self.pk})
    def __str__(self):
        return self.title+' - '+self.artist

class Song(models.Model):
   album = models.ForeignKey(Album, on_delete=models.CASCADE)
   title = models.CharField(max_length=50) 
   song_file = models.FileField(null=True)
   is_favorite = models.BooleanField(default='False')
   is_public = models.BooleanField(default='False')
   def __str__(self):
        return self.title 

music/forms.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django import forms
from .models import Album, Song
  
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password','email']
        
class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['title', 'song_file']

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ["username", "password"]

    def clean(self):
        if self.is_valid():
            if not authenticate(username=self.cleaned_data['username'], password=self.cleaned_data['password']):
                raise forms.ValidationError('Error, Invalid username or password!')

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields =  ['artist', 'title','is_public','album_file']

music/views.py
from django.shortcuts import render , redirect , get_object_or_404 , render_to_response
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.views.generic import CreateView , UpdateView , DeleteView , View , DetailView , ListView
from django.urls import reverse_lazy
from .models import Album , Song
from django.db.models import Q


from .forms import RegisterForm , LoginForm , SongForm ,AlbumForm
# Create your views here.

def Index(request):
    albums = Album.objects.all()
    songs = Song.objects.all()
    return render(request, 'music/index.html', {'songs':songs,"all_albums":albums} )

class DetailView(DetailView):
    model = Album
    template_name = 'music/detail.html'
    pk_url_kwarg = 'id'

# ------------------------------------------ album shit -------------------------------------------------------

class albums(ListView):
    model = Album
    template_name = "music/albums.html"
    context_object_name = "all_albums"
    def get_queryset(self):
        return  Album.objects.all()
def albumCreate(request):
    if not request.user.is_authenticated:
        return redirect('music:index')

    form = AlbumForm()
    if request.POST:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            form = AlbumForm()
            return redirect('music:index')

    return render(request, 'music/album_form.html', {'form':form})

class DeleteAlbum(DeleteView):
    model = Album
    pk_url_kwarg = 'id'

    success_url = reverse_lazy('music:albums')

def album_is_public(request , album_id):
    if not request.user.is_authenticated:
        return redirect('music:login')
    album = get_object_or_404(Album,pk=album_id)
    album.is_public = True
    album.save()
    songs = album.song_set.all()
    for song in songs :
        if song.is_public == False :
            song.is_public = True
            song.save()
        else :
            song.is_public = False
            song.save()
    
    return render(request , 'music/profile.html')



#---------------------------------------------- Songs shit -------------------------------------------------------

def CreateSong(request , id):
    form = SongForm(request.POST or None , request.FILES)
    album = get_object_or_404(Album,pk=id)
    if form.is_valid():
        album_songs = album.song_set.all()
        for s in album_songs :
            if s.title == form.cleaned_data.get("title"):
                context={'form':form , 'album':album , 'error_message':'You already made that song !'}
                return render(request, 'music/song_form.html', context)
        song = form.save(commit=False)
        song.album = album
        song.song_file = request.FILES['song_file']
        file_type = song.song_file.url.split('.')[-1].lower()
        AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
        if file_type not in AUDIO_FILE_TYPES : 
            context={'form':form , 'album':album , 'error_message':'Audio file must be WAV, MP3, or OGG'}
            return render(request, 'music/song_form.html', context)
        song.save()
        return render(request, 'music/detail.html', {'album': album})
    context={'form':form , 'album':album }
    return render(request, 'music/song_form.html', context)

def DeleteSong(request , album_id ,song_id):
    album = get_object_or_404(Album,pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request , 'music/detail.html',{'album':album})

def song_is_public(request , album_id , song_id):
    if not request.user.is_authenticated:
        return redirect('music:login')
    album = get_object_or_404(Album,pk=album_id)
    song = Song.objects.get(pk=song_id)
    album.is_public = True
    if song.is_public == False :
        song.is_public = True
    else :
        song.is_public = False
    album.save()
    song.save()
    return render(request , 'music/detail.html',{'album':album})

def song_is_favorite(request , album_id , song_id):
    if not request.user.is_authenticated:
        return redirect('music:login')
    album = get_object_or_404(Album,pk=album_id)
    song = Song.objects.get(pk=song_id)
    if song.is_favorite == False :
        song.is_favorite = True
    else :
        song.is_favorite = False
    song.save()
    return render(request , 'music/detail.html',{'album':album})

# --------------------------------------------- account shit ---------------------------------------------------------

def songs(request):
    songs = Song.objects.all()
    x='0'
    if request.POST :
        if request.POST.get('favorite') == "True" :
            x='1'
            songs = Song.objects.filter(is_favorite=request.POST.get('favorite'))

    return render(request, 'music/songs.html', {'songs':songs,'x':x})


class profile(ListView):
    model = Album
    template_name = "music/profile.html"
    context_object_name = "all_albums"
    def get_queryset(self):
        return  Album.objects.all()

def loginView(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('music:index')
            else:
                return render(request, 'music/account/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/account/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/account/login.html')

def Register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('music:profile')
               
    context = {
        "form": form,
    }
    return render(request, 'music/account/register.html', context)

def logoutView(request):
    logout(request)
    return redirect('music:index')

def getQuerySet(query=None):
    query_set = []
    for q in query.split(" "): # Convert it to list
        posts = Song.objects.filter(Q(title__icontains=q)).distinct()
        for post in posts:
            query_set.append(post)

    return list(set(query_set))

def dropdown(request):
    return render_to_response('music/base.html', {
        'songs': Song.objects.all()
        })

music/templates/music/albums.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12"> 
            <h3> Albums</h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                {% if user.request == album.user or album.is_public %}
                  
                    <div class="col-sm-7 col-lg-3">
                        <div class="thumbnail">
                            <a href="{% url 'music:detail' album.id %}">
                                <img src="{{album.album_file.url}}" style="height:100%;width:200%;" >
                            </a>
                            <div class="caption">
                                <h2><strong>{{ album.title }}</strong> - {{ album.artist }}</h2>
                                <!-- View Details -->
                                <a href="{% url 'music:detail' album.id %}" 
                                class="btn btn-primary btn-sm" role="button">View Details {{album.id}}</a>
                                {% if user.id == album.user.id  %}
                                    <!-- Delete Album -->
                                    <form action="{% url 'music:delete-album' album.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="album_id" value="{{ album.id }}" />
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                    <!-- Publish Album -->
                                    <a href="{% url 'music:album_public' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                        <span class="glyphicon glyphicon-share" {% if album.is_public %}style="color:orange;"{% endif %}></span>
                                    </a>
                                {% endif %}
                                <br>
                                <p>Uploaded by : {{album.user.username}}</p>
                            </div>
                        </div>
                    </div>
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endif %} <!-- show if public or user owner --> 
            {% endfor %} 
        {% else %}
            {% if user.is_authenticated %}
                <div class="col-sm-12">
                    <br>
                    <a href="{% url 'music:add-album' %}">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                        </button>
                    </a>
                </div>
            {% endif %}
            
        {% endif %}
        
    </div>
</div>
{% endblock  %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %} Viberr{% endblock title %}</title>
  {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{% static 'music/index_style.css' %}" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-inverse">
    <!-- inverse make it black   -->
    <div class="container-fluid">
      <!-- ???   -->

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <!-- this button appears when ecran is small   -->
          <span class="icon-bar"></span>
          <!-- those are lines -->
          <span class="icon-bar"></span>
        </button>
        <a  class="navbar-brand" href="{% url 'music:index' %}"> Sweet Pie </a>
      </div>


      <div class="collapse navbar-collapse" id="topNavBar">

        <ul class="nav navbar-nav">
          <li class="{% if request.path == '/albums/' %} active {% endif %}">
            <a href="{% url 'music:albums' %}">
              <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a>
          </li>
          <li class="">
            <a href="{% url 'music:songs' %}">
              <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a>
          </li>
        </ul>
        
        
        <ul class="nav navbar-nav navbar-right">
          {% if not user.is_authenticated %}
            <li class="">
              <a href="{% url 'music:login' %}" class="btn btn-dark" role="button">
                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Log in</a>
            </li>
          {% endif %}
 
          
          {% if user.is_authenticated %}
          <li class="">
            <a href="{% url 'music:profile' %}" class="btn btn-dark" role="button">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Welcome {{user.username}}</a>
          </li>
          <li class="">
            <a href="{% url 'music:add-album' %}">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Albums</a>
          </li>
          <li class="">
            <a href="{% url 'music:logout' %}">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log out</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block body %} {% endblock body %}
</body>

</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_file.url %}
                            <img src="{{ album.album_file.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="">View All</a></li>
                <li role="presentation"><a href="{% url 'music:add-song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Share</th>
                            <th>Actions</th>
                            <th>Download</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.title }}</td>
                                <td>
                                    
                                    <audio id="{{song.id}}" src="{{ song.song_file.url }}"></audio>
                                    <!--
                                    <div> 
                                    <button onclick="document.getElementById('player').play()">Play</button> 
                                    <button onclick="document.getElementById('player').pause()">Pause</button> 
                                    <button onclick="document.getElementById('player').volume += 0.1">Vol +</button> 
                                    <button onclick="document.getElementById('player').volume -= 0.1">Vol -</button> 
                                    </div>
                                    -->
                                    <button onclick="document.getElementById('{{song.id}}').play()" 
                                    type="button" class="btn btn-success btn-xs">
                                     <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                    </button>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <button onclick="document.getElementById('{{song.id}}').pause()" class="btn btn-warning btn-xs">
                                        <span class="glyphicon glyphicon-pause"></span>&nbsp; pause
                                    </button>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-share {% if song.is_public %}active{% endif %}"></span></a>
                                </td>

                                <td>
                                    <form action="{% url 'music:song-delete' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    
                                    <a class="btn btn-info btn-xs" href="{{song.song_file.url}}"><span class="glyphicon glyphicon-download-alt"></span>&nbsp; Download </a>
                                      
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html'%}
{% block body %}
<div style="margin-top:100px;" class="container mt-5">
    <div style="text-align: center">

      <h1>Make Your Playlist</h1><br>
      <p class="lead">Come create your playlist and listen to your favorite songs ... All you need to do is sign up!</p>
      <div class="text-center">
        <a href="{% url 'music:register' %}"  class="btn btn-primary btn-lg">Register</a>
        <button style="margin:10px;" class="btn btn-info btn-lg">Learn more</button>
      </div>
 </div>
  

{% endblock body %}

music/templates/music/profile.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}
{% with temp='0' %} {% endwith %}
{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12"> 
            <h3>{{ user.username|capfirst }} Albums</h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}   
                {% if user.id == album.user.id  %}      
                        {% with temp='1' %} {% endwith %}   
                        <div class="col-sm-7 col-lg-3">
                            <div class="thumbnail">
                                <a href="{% url 'music:detail' album.id %}">
                                    <img src="{{album.album_file.url}}" style="height:100%;width:200%;" >
                                </a>
                                <div class="caption">
                                    <h2>{{ album.title }}</h2>
                                    <h4>{{ album.artist }}</h4>

                                    <!-- View Details -->
                                    <a href="{% url 'music:detail' album.id %}" 
                                    class="btn btn-primary btn-sm" role="button">View Details {{album.id}}</a>
                                        <!-- Delete Album -->
                                        <form action="{% url 'music:delete-album' album.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                                            <button type="submit" class="btn btn-default btn-sm">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        </form>
                                        <!-- Publish Album -->
                                        <a href="{% url 'music:album_public' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                            <span class="glyphicon glyphicon-share" {% if album.is_public %}style="color:orange;"{% endif %}></span>
                                        </a>
                                        
                                        
                                    
                                </div>
                            </div>
                        </div>
                        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endif %}
            {% endfor %} 
        {% endif %}
        
    </div>
</div>
{% endblock  %}

music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}{{ song.album }}{% endblock %}

{% block body %}
<div class="container-fluid songs-container">
       
        <!-- Right Song Info -->
        <div class="">
            <form class="form-group"  method="post">
                {% csrf_token %}
                <h3>Filter your songs : </h3>
                <select name="favorite">
                  <option value="False" >All</option>
                  <option value="True"  {% ifequal x '1' %} selected {% endifequal %}>My favorite</option>
                </select>
                <input  class="btn btn-success btn-sm"  type="submit" value="Apply">
            </form>
            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Favorites Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Share</th>
                            <th>Actions</th>
                            <th>Download</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for song in songs %}
                            {% if song.is_public or user.id == song.album.user.id %}
    
                            <tr>
                                <td>{{ song.title }}</td>
                                <td>
                                    
                                    <audio id="{{song.id}}" src="{{ song.song_file.url }}" hidden></audio>
                                    <!--
                                    <div> 
                                    <button onclick="document.getElementById('player').play()">Play</button> 
                                    <button onclick="document.getElementById('player').pause()">Pause</button> 
                                    <button onclick="document.getElementById('player').volume += 0.1">Vol +</button> 
                                    <button onclick="document.getElementById('player').volume -= 0.1">Vol -</button> 
                                    </div>
                                    -->
                                    <button onclick="document.getElementById('{{song.id}}').play()" 
                                    type="button" class="btn btn-success btn-xs">
                                     <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                    </button>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <button onclick="document.getElementById('{{song.id}}').pause()" class="btn btn-warning btn-xs">
                                        <span class="glyphicon glyphicon-pause"></span>&nbsp; pause
                                    </button>
                                </td>
                            
                                <td>
                                    {% if user.id == song.album.user.id  %}
                                    <a href="{% url 'music:song_favorite' song.album.id song.id %}" class="btn-favorite" role="button">
                                        <span class="glyphicon glyphicon-star" {% if song.is_favorite %}style="color:orange;"{% endif %}></span>
                                    </a>                                    
                                    {% endif %}
                                </td>
                                <td>
                                    {% if user.id == song.album.user.id  %}
                                    <a href="{% url 'music:song_public' song.album.id song.id %}" class="btn-favorite" role="button">
                                        <span class="glyphicon glyphicon-share" {% if song.is_public %}style="color:orange;"{% endif %}></span>
                                    </a>                                       
                                    {% endif %}
                                </td>
                                
                                <td>
                                    {% if user.id == song.album.user.id  %}
                                    <form action="{% url 'music:song-delete' song.album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                    {% endif %}
                                </td>
                               
                                <td>
                                    
                                    <a class="btn btn-info btn-xs" href="{{song.song_file.url}}"><span class="glyphicon glyphicon-download-alt"></span>&nbsp; Download </a>
                                      
                                </td>
                            </tr>
                        {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>


{% endblock %}